[package]
name = "wasm-fzf"
version = "0.1.0"
authors = ["kmszk <kmszk.kent@gmail.com>"]

[dependencies]
wasm-bindgen = "0.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"

[lib]
crate-type = ["cdylib"]
